plugins:
  - jekyll-multiple-languages-plugin

languages: ["cs", "en"]
exclude_from_localizations: ["assets"]
assetsPath: "/assets"

sass:
  implementation: sass-embedded

collections:
  industries:
  benefits:
  pains:
  features:
  customer-steps:
  partners:
